box: "sle15sp5"
short: "rancher2"
fqdn: "rancher2.labs.suse.com"
subnet: "primarysubnet"
ipaddress: ".42"
public: "true"
cpus: "2"
memory: "8192"
provisioning: "k3s/bootstrap.sh"
files: "k3s/files"
environment: "SLE15"
static: "N"