box: "sle15sp5"
short: "ranch0"
fqdn: "ranch0.labs.suse.com"
subnet: "primarysubnet"
ipaddress: ".40"
public: "true"
cpus: "2"
memory: "8192"
provisioning: "rke2/bootstrap.sh"
files: "rke2/files"
environment: "SLE15"
static: "N"