box: "sle15sp5"
short: "ranch-utils"
fqdn: "ranch-utils.labs.suse.com"
subnet: "primarysubnet"
ipaddress: ".40"
public: "true"
cpus: "2"
memory: "8192"
provisioning: "utils/bootstrap.sh"
files: "utils/files"
environment: "SLE15"
static: "N"