box: "sle15sp5"
short: "trento-sap1"
fqdn: "trento-sap1.labs.suse.com"
subnet: "primarysubnet"
ipaddress: ".43"
public: "true"
cpus: "2"
memory: "8192"
provisioning: "trento/bootstrap.sh"
files: "trneto/files"
environment: "SLE15"
static: "N"