box: "sle15sp5"
short: "kvm-node2"
fqdn: "kvm-node2.labs.suse.com"
subnet: "primarysubnet"
ipaddress: ".52"
cpus: "1"
memory: "1024"
provisioning: "joining-nodes/bootstrap.sh"
files: "joining-nodes/files"
environment: "SLE15"
static: "N"