box: "sle15sp5"
short: "kvm-node3"
fqdn: "kvm-node3.labs.suse.com"
subnet: "primarysubnet"
ipaddress: ".53"
cpus: "4"
memory: "8192"
provisioning: "joining-nodes/bootstrap.sh"
files: "joining-nodes/files"
environment: "SLE15"
static: "N"