box: "sle15sp5"
short: "kvm-node1"
fqdn: "kvm-node1.labs.suse.com"
subnet: "primarysubnet"
ipaddress: ".51"
cpus: "4"
memory: "8192"
provisioning: "init-node/bootstrap.sh"
files: "init-node/files"
environment: "SLE15"
static: "N"