box: "sle15sp5"
short: "nfs"
fqdn: "nfs.labs.suse.com"
subnet: "primarysubnet"
ipaddress: ".50"
cpus: "1"
memory: "1024"
provisioning: "nfs/bootstrap.sh"
files: "nfs/files"
environment: "SLE15"
static: "N"