box: "sle15sp4"
short: "build15sp4"
fqdn: "build15sp4.labs.suse.com"
subnet: "primarysubnet"
ipaddress: ".83"
cpus: "1"
memory: "8192"
provisioning: "build/bootstrap.sh"
files: "build/files"
environment: "SLE15"
static: "N"