box: "sle15sp4"
short: "kvm15sp4"
fqdn: "kvm15sp4.labs.suse.com"
subnet: "primarysubnet"
ipaddress: ".84"
cpus: "1"
memory: "8192"
provisioning: "kvm/bootstrap.sh"
files: "kvm/files"
environment: "SLE15"
static: "N"