name: Build with Nuitka

on:
  push:
    branches:
      - gh-actions-LabBreakers
  pull_request:
    branches:
      - gh-actions-LabBreakers

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Install Python 3.6 development headers
      run: |
        sudo apt-get update
        sudo apt-get install -y python3.6-dev

    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    
    - name: Install virtualenv
      run: |
        pip3.6 install virtualenv
        
    - name: Set up virtual environment
      run: |
        python3.6 -m venv venv
        echo "VIRTUAL_ENV=$(pwd)/venv" >> $GITHUB_ENV
        echo "$(pwd)/venv/bin" >> $GITHUB_PATH
      working-directory: LabBreakers/sumalabs/src

    - name: Install dependencies
      run: |
        . venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: LabBreakers/sumalabs/src     

    - name: Find grapheme data file location
      run: |
        source activate
        echo "GRAPHENE_DATA_FILE=$(python -c 'import os, grapheme; print(os.path.join(grapheme.__path__[0], "data", "grapheme_break_property.json"))')" >> $GITHUB_ENV

    - name: Build with Nuitka
      run: |
        source activate
        unset PYTHONHOME
        unset PYTHONPATH
        echo "Python Version:"
        python --version
        echo "Python Path:"
        which python
        python -m nuitka sumalabs.py --onefile --standalone --output-dir=${GITHUB_WORKSPACE}/LabBreakers/sumalabs/bin --output-filename=sumalabs  --include-data-file="${GRAPHENE_DATA_FILE}=grapheme/data/grapheme_break_property.json" --remove-output
      working-directory: LabBreakers/sumalabs/src

    - name: Move binary to desired locations
      run: |
        cp LabBreakers/sumalabs/bin/sumalabs provisioners/lab/suma/server/files/sumalabs
        cp LabBreakers/sumalabs/src/sumalabs_completion.sh provisioners/lab/suma/server/files/sumalabs_completion.sh

    - name: Upload build artifact (LabBreakers/sumalabs/bin/)
      uses: actions/upload-artifact@v2
      with:
        name: binary
        path: LabBreakers/sumalabs/bin/sumalabs

    - name: Upload build artifact (second_location)
      uses: actions/upload-artifact@v2
      with:
        name: binary_second_location
        path: provisioners/lab/suma/server/files/sumalabs

    - name: Clean up venv folder
      run: |
        rm -rf venv    

    - name: Commit files
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add LabBreakers/sumalabs/bin/sumalabs
        git add provisioners/lab/suma/server/files/sumalabs
        git commit -m "Add changes"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-actions-LabBreakers
